import React, { useState } from "react";

import { useNavigate } from "react-router-dom";

import BlurFade from "../Components/magicui/BlurFade";
import Features from "../Components/Features";

const Home = () => {
  const navigate = useNavigate();
  const [hoveredIndex, setHoveredIndex] = useState(null);

  return (
    <section className="flexCenter min-h-[77vh] flex-col">
      {/* ========= Home PAge ========= */}
      {/* <header className="home-gradient text-white flexCenter flex-col h-screen text-center p-6 gap-y-6 w-full">
        <BlurFade delay={0.25} inView>
          <h1 className="text-4xl md:text-5xl font-bold pb-5 logo">
            Welcome to MyApp
          </h1>
        </BlurFade>
        <BlurFade delay={0.25 * 2} inView>
          <p className="text-lg md:text-xl mb-6 leading-9 sm:leading-10 text-center max-w-[470px] gradient-text3">
            Secure authentication and seamless authorization with the MERN stack
            and JWT.
          </p>
        </BlurFade>
        <BlurFade delay={0.25 * 4} inView>
          <button
            onClick={() => navigate("/signup")}
            className=" hover-cursorCSS bg-transparent border-white border-2 px-6 py-3 rounded-lg text-lg font-semibold transition-all hover:scale-110 gradient-text2"
          >
            Get Started
          </button>
        </BlurFade>
      </header> */}

      <header className="home-gradient flexCenter flex-col h-screen text-center p-6 gap-y-6 w-full">
        <BlurFade delay={0.25} inView>
          <h1 className="text-4xl md:text-5xl font-bold pb-5f font3">
            Welcome to QuizifyAI
          </h1>
        </BlurFade>

        {/* <BlurFade delay={0.25 * 2} inView>
          <p className="text-lg md:text-xl mb-6 leading-9 sm:leading-10 text-center max-w-[470px] gradient-text3">
            Secure authentication and seamless authorization with the MERN stack
            and JWT.
          </p>
        </BlurFade> */}

        <BlurFade delay={0.25 * 3} inView>
          <p className="gradient-text3 text-md md:text-lg pb-4 max-w-[600px] mx-auto leading-8 ">
            Dive into a world of quizzes generated by AI. Explore various topics
            and test your knowledge in a fun, engaging way. Whether you're
            studying for an exam or just want to challenge yourself, QuizifyAI
            has you covered.
          </p>
        </BlurFade>

        {/* <BlurFade delay={0.25 * 4} inView>
          <h2 className="text-2xl md:text-3xl font-semibold mt-4 mb-2">
            Features
          </h2>
          <ul className="mb-4 font-raleway text-left max-w-[500px] mx-auto flex flex-wrap gap-y-4 text-xs  ">
            <li>🔒 Advanced JWT Authentication</li>
            <li>📝 AI-Generated Quizzes on Any Topic</li>
            <li>📊 Comprehensive Analytics for Your Performance</li>
            <li>🌐 Mobile-Friendly and Easy to Use</li>
            <li>🔍 Explore a Wide Range of Subjects</li>
          </ul>
        </BlurFade> */}

        <BlurFade delay={0.25 * 5} inView>
          <button
            onClick={() => navigate("/allquiz")}
            className="hover-cursorCSS bg-transparent border-white border-2 px-6 py-3 rounded-lg text-lg font-semibold transition-all hover:scale-110 gradient-text2"
          >
            Get Started
          </button>
        </BlurFade>

        <BlurFade delay={0.25 * 6} inView>
          <p className="text-sm md:text-md mt-6 text-white">
            Join thousands of users and start your quiz journey today!
          </p>
        </BlurFade>
      </header>

      {/* ========= FEATURES ========= */}
      <Features />
    </section>
  );
};

export default Home;
